version: 2.1

orbs: # declare what orbs we are going to use
  node: circleci/node@4.6.0

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.6.0
      - environment:
          TEST_ENV_VARIABLE: ramesh
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
          environment:
            TEST_ENVIRON_VARIABLE: ramesh
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm run test
