version: 2.1

orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.6.0
      - environment:
          TEST_ENV_VARIABLE: ramesh
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install dependencies
          command: npm install
          environment:
            TEST_ENVIRON_VARIABLE: ramesh
      - run:
          name: Run Tests
          command: npm run test
